### PR TITLE
Feature automate data processing

### PR DESCRIPTION
**Pull request by willcattoneeca**
This PR introduces a scripted process for the postprocessing of TIMES-NZ output through to the RShiny visualization. It includes a scripted auto-generation of summary figures for the "Key Insights" graph, as well as the main table that is presented in the Data Explorer.

https://eeca-nz.shinyapps.io/TIMES_V2_1_3/

I am marking this PR as 'draft' because I haven't updated the README files but the work is otherwise complete. Essentially (once your system is configured) you can run `python .\scripts\run_all_processes.py 2.1.3` and it will retrieve the model files created by VEDA, run the scenarios, postprocess their outputs, and launch the app (locally on your machine).

At present we can't auto-generate the assumptions table that accompanies the key insights graph, so this is left as a TODO item for the future. Similarly, there are statements recorded in CSV files in the 'data' directory of the RShiny tool that will need to be updated before we can publish an updated version of the RShiny visualisation.

### CODE REVIEW

**Comment by billgeo** [comment]
Comment on side by side comparison of the visualisation tool:

1. Key Insights: Renewable energy % is significantly different across both scenarios. Is that understood enough to write something about in the changelog? 
2. Key Insights: Elec Generation from Solar is significantly different in Tui. I presume we know why and can explain that?


Maybe it would be good to add a changelog or something similar to this PR that can be the basis of the changelog for the tool?

**Review by billgeo — APPROVED** [review]
Compared the visualisations side by side and had a look at some of the python code. Skipped the R code and configuration. It's a lot to read!

Would be good to someone else review the code if possible. Maybe @raulbento-eeca ?

**Review by billgeo — APPROVED** [review]
LGTM.

**Review by Achieeca — COMMENTED** [review]
I was able to run all the code scripts locally and get the RShiny visualization. I had to set paths for R and Python versions before running the scripts. 

Also compared the visuals side by side and noticed that the fossil fuel consumption (Commercial sector, Tui scenario) shows a slight increase in 2030 before gradually decrease, which is different to the published version.

**Review by ThomasHP-EECA — APPROVED** [review]

**Pull request merged**
