### PR TITLE
Convert XLS files to XLSX to be compatible with xl2times

### PR DESCRIPTION
**Pull request by siddharth-krishna**
`xl2times` does not support the old XLS file format, so this PR converts the 2 files in the old format to the newer XLSX format.

I don't have Excel, so I did this using an online tool. Once #63 is merged in, we can use `raw_tables.txt` to verify that the changes in this PR did not change the contents of the two files. EDIT: alas, we can't use it because the old XLS files were not included in `raw_tables.txt` (doh!). Is there some way to check that the new files are equivalent to the old ones?

### CODE REVIEW

**Review by willcattoneeca — APPROVED** [review]
Awesome, thanks Sid!

**Review by willcattoneeca — APPROVED** [review]
Awesome, thanks Sid!

**Comment by siddharth-krishna** [comment]
Thanks Will. I can push the new raw tables file in a few minutes to make this pass CI.

**Comment by willcattoneeca** [comment]
> Thanks Will. I can push the new raw tables file in a few minutes to make this pass CI.

Ah, have already done this!

**Review by searleluke — APPROVED** [review]

**Pull request merged**
